# change the followings to match your Github username and repo name
baseurl: "/blog" # the name of your github repo
url: "https://tomtietz.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Tom's Blog"
description: Personal Blog

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Tom Tietz
author-bio: false # change to false to hide
author-image: garfield.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Articles
  permalink: blog
#- text: Resume
#  permalink: resume

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/TomTietz
linkedin: https://www.linkedin.com/in/tom-j-tietz/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics G-ID
google-analytics: G-ZG74M851QX

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag

